version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:5.6.35
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todolist
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
